/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.views;

import com.software.Control.ControlDBs;
import com.software.DTO.DTOUser;
import javax.swing.JOptionPane;

/**
 *
 * @author drago
 */
public class Login extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_DB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Puerto = new javax.swing.JTextField();
        jTextField_Instancia = new javax.swing.JTextField();
        jTextField_IP = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_conection = new javax.swing.JButton();
        jTextField_User = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setText("de datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBox_DB.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jComboBox_DB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Mysql", "Postgres", "SQLServer" }));
        jComboBox_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DBActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_DB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 310, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Instancia");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("IP Servidor");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setText("Puerto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextField_Puerto.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jTextField_Puerto.setText("1521");
        jPanel2.add(jTextField_Puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));

        jTextField_Instancia.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jTextField_Instancia.setText("XE");
        jPanel2.add(jTextField_Instancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 190, -1));

        jTextField_IP.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jTextField_IP.setText("localhost");
        jPanel2.add(jTextField_IP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, -1));

        btn_cancel.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 181, 130, 40));

        btn_conection.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btn_conection.setText("Conectar");
        btn_conection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_conection, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 181, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 470, 240));

        jTextField_User.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jTextField_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UserActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel7.setText("Motor de base");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 30));

        jPasswordField1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 310, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectionActionPerformed

        String db = jComboBox_DB.getSelectedItem().toString();
        if (null != db) switch (db) {
            case "Oracle", "Postgres" -> {
                System.out.println("DB: " + db + " user: " + jTextField_User.getText() + " pass: " + jPasswordField1.getText() + " Instancia: " + jTextField_Instancia.getText() + "IP" + jTextField_IP.getText() + " puerto: " + jTextField_Puerto.getText());
                DTOUser dtoUser = new DTOUser(db, jTextField_User.getText(), jPasswordField1.getText(), jTextField_Instancia.getText(), jTextField_IP.getText(), jTextField_Puerto.getText());
                ControlDBs control = new ControlDBs();
                control.setDTO(dtoUser);
                System.out.println(dtoUser.getDB());
                if (control.Login() != null) {
                    JOptionPane.showMessageDialog(null, "Conectado Correctamente");
                    IDE_DBs ide = new IDE_DBs(dtoUser);
                    MainView.Desktop.add(ide);
                    ide.show();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                }
            }
            case "SQLServer" -> {
                DTOUser dtoUser = new DTOUser(db, jTextField_User.getText(), jPasswordField1.getText(), jTextField_Instancia.getText(), jTextField_IP.getText(),jTextField_Puerto.getText());
                System.out.println("db: " + jTextField_Puerto.getText() + " User: " + jTextField_User.getText() + " pass: " + jPasswordField1.getText() + " DB: "+jTextField_Instancia+" IP SERVIDOR: " + jTextField_IP.getText() + " Puerto: " + jTextField_Puerto.getText());
                ControlDBs control = new ControlDBs();
                control.setDTO(dtoUser);
                System.out.println(dtoUser.getDB());
                if (control.Login() != null) {
                    JOptionPane.showMessageDialog(null, "Conectado Correctamente");
                    IDE_DBs ide = new IDE_DBs(dtoUser);
                    MainView.Desktop.add(ide);
                    ide.show();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                }                      }
            case "Mysql" -> {
                System.out.println("DB: " + db + " user: " + jTextField_User.getText() + " pass: " + jPasswordField1.getText() + " Instancia: " + jTextField_Instancia.getText() + "IP" + jTextField_IP.getText() + " puerto: " + jTextField_Puerto.getText());
                DTOUser dtoUser = new DTOUser(db, jTextField_User.getText(), jPasswordField1.getText(), jTextField_Instancia.getText(), jTextField_IP.getText(), jTextField_Puerto.getText());
                ControlDBs control = new ControlDBs();
                control.setDTO(dtoUser);
                System.out.println(dtoUser.getDB());
                if (control.Login() != null) {
                    JOptionPane.showMessageDialog(null, "Conectado Correctamente");
                    IDE_DBs ide = new IDE_DBs(dtoUser);
                    MainView.Desktop.add(ide);
                    ide.show();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                }                      }
            default -> {
                }
        }
    }//GEN-LAST:event_btn_conectionActionPerformed

    private void jComboBox_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DBActionPerformed
        String db = jComboBox_DB.getSelectedItem().toString();
        if (null != db) switch (db) {
            case "SQLServer" -> {
                jLabel4.setText("Base de datos");
                jTextField_IP.setText("localhost");
                jTextField_Instancia.setText("empresa");
                jTextField_Puerto.setText("1433");
                jTextField_User.setText("sharon");
                jPasswordField1.setText("contrasharon");
            }
            case "Oracle" -> {
                jLabel4.setText("Instancia");
                jTextField_Puerto.setText("1521");
                jTextField_IP.setText("localhost");
                jTextField_Instancia.setText("XE");
                jTextField_User.setText("brianlml");
                jPasswordField1.setText("brian5607364");
            }
            case "Mysql" -> {
                jLabel4.setText("Base de datos");
                jTextField_Puerto.setText("3306");
                jTextField_Instancia.setText("pruebasfinales");
                jTextField_User.setText("BrianMysql");
                jPasswordField1.setText("Hola123456");
                jTextField_IP.setText("localhost");
            }
            case "Postgres" -> {
                jLabel4.setText("Base de datos");
                jTextField_Puerto.setText("5433");
                jTextField_Instancia.setText("Prueba");
                jTextField_IP.setText("localhost");
                jTextField_User.setText("BrianPostgres");
                jPasswordField1.setText("Hola123456");
            }
            default -> {
            }
        }

    }//GEN-LAST:event_jComboBox_DBActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jTextField_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UserActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_conection;
    private javax.swing.JComboBox<String> jComboBox_DB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_IP;
    private javax.swing.JTextField jTextField_Instancia;
    private javax.swing.JTextField jTextField_Puerto;
    private javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables
}
