/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.views;

import javax.swing.UIManager;

/**
 *
 * @author drago
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        try {
            UIManager.LookAndFeelInfo looks[] = UIManager.getInstalledLookAndFeels();
            // 0-Swing, 1-Mac, 2-?, 3-Windows, 4-Old Windows
            UIManager.setLookAndFeel(looks[3].getClassName());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_opciones = new javax.swing.JMenu();
        jMenuItem_login = new javax.swing.JMenuItem();
        JMenuItem_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 810));

        JMenu_opciones.setText("Opciones");

        jMenuItem_login.setText("Nueva Sesion");
        jMenuItem_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_loginActionPerformed(evt);
            }
        });
        JMenu_opciones.add(jMenuItem_login);

        JMenuItem_exit.setText("Salir");
        JMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_exitActionPerformed(evt);
            }
        });
        JMenu_opciones.add(JMenuItem_exit);

        jMenuBar1.add(JMenu_opciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_loginActionPerformed
        Login login = new Login();
        Desktop.add(login);
        login.show();
    }//GEN-LAST:event_jMenuItem_loginActionPerformed

    private void JMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItem_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem JMenuItem_exit;
    private javax.swing.JMenu JMenu_opciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_login;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
